### PR TITLE
Sidebar customisation improvements

### PR DESCRIPTION
**Pull request by allmarkedup**
This PR adds config options to:

* Customise the order of the nav panels in the sidebar
* Hide or show the search/filter box for both previews and pages

## Sidebar panel order

This PR adds a `preview_inspector.sidebar_panels` config option that allows for the reordering (or omitting) of section panels in the Lookbook sidebar.

  ```ruby
  config.lookbook.preview_inspector.sidebar_panels = [:pages, :previews]
  ```

The default value is `[:previews, :pages]`. [Documentation here](https://deploy-preview-556--lookbook-docs.netlify.app/guide/config#preview_inspector.sidebar_panels)

## Search/filter inputs

This PR adds `preview_search` and `page_search` config options to hide or show the filter box UI for previews and pages respectively.

  ```ruby
  config.lookbook.preview_search = false # default: true 
  config.lookbook.page_search = true # default: false
  ```

For backwards compatibility preview search is enabled by default, but pages search is not.

Documentation for [pages](https://deploy-preview-556--lookbook-docs.netlify.app/guide/config#page_search) and [previews](https://deploy-preview-556--lookbook-docs.netlify.app/guide/config#preview_search).

### CODE REVIEW

**Comment by cody-clio** [comment]
@allmarkedup I've pulled the gem locally, and I can see that the section configuration is working, but I do not see the search appearing. 

Configuration setup: 

```
config.lookbook.preview_inspector.sidebar_panels = [:pages, :previews]
config.lookbook.preview_search = true
config.lookbook.page_search = true
```

Even if I disable all the configurations, I'm not seeing the search show up any longer: 

Screenshot 2023-11-22 at 10 01 41 AM

**Comment by allmarkedup** [comment]
@cody-clio argh sorry, my bad, I was rushing things to get the PR up before I had to head out and made a stupid typo. Should be fixed now!

**Comment by cody-clio** [comment]
Looks great! Thanks for making these changes! Excited to use them. 

Screenshot 2023-11-22 at 1 51 37 PM

**Comment by allmarkedup** [comment]
@cody-clio Awesome, thanks for the feature requests that prodded me into action :) I'll merge this now and hopefully get a new release out in the next day or two.

**Pull request merged**
